name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install nium
      run: |
        curl https://nim-lang.org/choosenim/init.sh -sSf | sh
        export PATH=~/.nimble/bin:$PATH
        choosenim 1.0.0
        nim -v
        nimble -v
    - name: Run test
      run: nimble test --verbose
