name: Release
on:
  release:
    types: created
jobs:
  macOS:
    runs-on: macOS-10.14
    steps:
      - uses: actions/checkout@v1
      - name: Build artifact
        run: |
          brew update
          brew install nim@1.0.0
          nimble build -d:ssl
          tar -zcvf macOS.tar.gz nim_todo_issue
      - name: Upload artifact
        uses: skx/github-action-publish-binaries@release-0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'macOS.tar.gz'
  ubuntu:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Build artifact
      run: |
        curl https://nim-lang.org/choosenim/init.sh -sSf > .choosenim.sh
        . .choosenim.sh -y
        export PATH=~/.nimble/bin:$PATH
        nimble build -d:ssl
        tar -zcvf ubuntu.tar.gz nim_todo_issue
      env:
        CHOOSENIM_CHOOSE_VERSION: '1.0.0'
    - name: Upload artifacts
      uses: skx/github-action-publish-binaries@release-0.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'ubuntu.tar.gz'
